#!/bin/bash

/scripts/postwwwacct.lvemanager.bak "$@"

# CloudLinux Stuff
/usr/share/l.v.e-manager/cpanel/hooks/l.v.e-manager_postwwwacct_hook.pl "$@"   #l.v.e-manager
/usr/share/cagefs/cpanel/cagefs_postwwwacct_hook.pl "$@"   #CageFS Version 2.0
