#!/bin/bash
# Copyright (c) 2008-2013 http://datasource.pt/ 

cat << 'EOF' > /usr/local/apache/conf/includes/pre_main_2.conf
## QoS Settings
<IfModule mod_qos.c>
    # handles connections from up to 100000 different IPs
    QS_ClientEntries 100000
    # will allow only 50 connections per IP
    QS_SrvMaxConnPerIP 50
    # maximum number of active TCP connections is limited to 256
    MaxClients              256 
    # disables keep-alive when 70% of the TCP connections are occupied:
    QS_SrvMaxConnClose      180
    # minimum request/response speed (deny slow clients blocking the server, ie. slowloris keeping connections open without requesting anything):
    QS_SrvMinDataRate       150 1200
    # and limit request header and body (carefull, that limits uploads and post requests too):
    # LimitRequestFields      30
    # QS_LimitRequestBody     102400
</IfModule>
EOF

cat << 'EOF' > /usr/local/apache/conf/includes/pre_virtualhost_global.conf
<IfModule mod_fcgid.c>
AddHandler fcgid-script .php5 .php4 .php .php3 .php2 .phtml
FCGIWrapper /usr/local/cpanel/cgi-sys/php5 .php5
FCGIWrapper /usr/local/cpanel/cgi-sys/php5 .php4
FCGIWrapper /usr/local/cpanel/cgi-sys/php5 .php
FCGIWrapper /usr/local/cpanel/cgi-sys/php5 .php3
FCGIWrapper /usr/local/cpanel/cgi-sys/php5 .php2
FCGIWrapper /usr/local/cpanel/cgi-sys/php5 .phtml
## PARA SERVIDORES PARTILHADOS ##
FcgidMaxRequestsPerProcess 1000
FcgidMinProcessesPerClass  0
FcgidMaxProcessesPerClass  8
FcgidMaxProcesses          100
FcgidIdleTimeout           60
FcgidProcessLifeTime       120
FcgidIdleScanInterval      30
FcgidIOTimeout             2000
FcgidFixPathinfo           1
FcgidMaxRequestLen         1073741824

## PARA VPS ##
#FcgidMaxRequestsPerProcess 1000
#FcgidMinProcessesPerClass  0
#FcgidMaxProcessesPerClass  8
#FcgidMaxProcesses          25
#FcgidIdleTimeout           60
#FcgidProcessLifeTime       120
#FcgidIdleScanInterval      30
#FcgidIOTimeout             2000
#FcgidFixPathinfo           1
#FcgidMaxRequestLen         1073741824

</IfModule>


###################################################
HostnameLookups      Off

## PARA SERVIDORES PARTILHADOS ##
#<IfModule worker.c>
#ServerLimit          2048
#ThreadLimit          100
#StartServers         10
#inSpareThreads      30
#axSpareThreads      100
#hreadsPerChild      64
#MaxClients           1024
#MaxRequestsPerChild  5000
#</IfModule>

## PARA VPS apache 2.2 ##
#<IfModule prefork.c>
#StartServers        1
#MinSpareServers     1
#MaxSpareServers     5
#ServerLimit         50
#MaxClients          50
#MaxRequestsPerChild 1000
#</IfModule>

## PARA VPS apache 2.4 ##
#<IfModule prefork.c>
#StartServers           1
#MinSpareServers        1
#MaxSpareServers        5
#ServerLimit            50
#MaxRequestWorkers      50
#MaxConnectionsPerChild 1000
#</IfModule>


###################################################
<IfModule mod_deflate.c>
    # Force deflate for mangled headers developer.yahoo.com/blogs/ydn/posts/2010/12/pushing-beyond-gzipping/
    SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)s*,?s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
    RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding

    #SetOutputFilter DEFLATE
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/x-javascript application/json
    # Netscape 4.x has some problems…
    BrowserMatch ^Mozilla/4 gzip-only-text/html
    # Netscape 4.06-4.08 have some more problems
    BrowserMatch ^Mozilla/4\.0[678] no-gzip
    # MSIE masquerades as Netscape, but it is fine
    BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
    # Don’t compress images
    SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|png)$ no-gzip dont-vary
    # Don’t compress compressed files
    SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|bz2|sit|rar|7z|gz)$ no-gzip dont-vary
    # Don’t compress pdf files
    SetEnvIfNoCase Request_URI \.(?:pdf|doc)$ no-gzip dont-vary
    # Don’t compress MOVIES & AUDIO
    SetEnvIfNoCase Request_URI \.(?:avi|mov|mp3|mp4|m4v|flv|rm|ogg|wav|mid)$ no-gzip dont-vary
    # Make sure proxies don’t deliver the wrong content
    Header append Vary User-Agent env=!dont-vary
    #DeflateCompressionLevel 9
    #DeflateMemLevel 9
    #DeflateWindowSize 15
    #DeflateBufferSize 8096
    #DeflateBufferSize 1024
</IfModule>

<ifModule mod_expires.c>  
    ExpiresActive On  
    ExpiresDefault "access plus 1 week"  
    ExpiresByType image/x-icon "access plus 2592000 seconds"  
    ExpiresByType image/jpeg "access plus 2592000 seconds"  
    ExpiresByType image/png "access plus 2592000 seconds"  
    ExpiresByType image/gif "access plus 2592000 seconds"  
    ExpiresByType application/x-shockwave-flash "access plus 2592000 seconds"  
    ExpiresByType text/css "access plus 604800 seconds"  
    ExpiresByType text/javascript "access plus 216000 seconds"  
    ExpiresByType application/javascript "access plus 216000 seconds"  
    ExpiresByType application/x-javascript "access plus 216000 seconds"  
    ExpiresByType text/html "access plus 600 seconds"  
    ExpiresByType application/xhtml+xml "access plus 600 seconds"  
</ifModule>  

<VirtualHost 127.0.0.1:6081>
    ServerName 127.0.0.1
    DocumentRoot /usr/local/apache/htdocs
    ServerAdmin servidores@datasource.pt
    UserDir disabled

<Location /whm-server-status>
    SetHandler server-status
    Order deny,allow
    Deny from all
    Allow from all
</Location>
</VirtualHost>
EOF
